### ISSUE TITLE
Unity Native Scripting vs. Unity native plugin

### ISSUE THREAD

**Issue by amirea** [jacksondunstan/UnityNativeScripting#1]
Hello.
I'm very much interested in coding in C++ in Unity and as I was looking for a (proper) way, I stumbled upon this repository. I read the readme and I still have a couple of things unclear.
I know C++, I know Unity but I don't know a bit about how they can be made to work together, nor by your solution neither by official ones.
I think it would be great if you clearly stated differences (ups/downs) between using your Unity Native Scripting solution and the ones that are already offered by Unity (f.i. native plugin). Please make this visible in the readme so people would go with yours without hesitation.

**Comment by jacksondunstan** [comment]
Hi amirea,

I'm glad you're interested in C++ scripting and considering using this project. I've been detailing explicitly how this project works as I implement it. The basics are in the [first part](https://jacksondunstan.com/articles/3938) of my (so far) 20 part blog series. There's actually no difference between this project and a native plugin. As the readme explains in the "Project Structure" section:

> All of your code, plus a few bindings, will exist in a single "native" C++ plugin.

Please let me know if you have any more questions or if you run into any issues using the project.

Best,
-Jackson
