### ISSUE TITLE
Assets/Plugins/Editor/NativeScript.dll does not exist

### ISSUE THREAD

**Issue by 1028405207** [jacksondunstan/UnityNativeScripting#20]
When I Run  Your Project , It Appear Some Wrong "Assets/Plugins/Editor/NativeScript.dll does not exist" How Can I Solve it /.

**Comment by jacksondunstan** [comment]
Hi, please follow the "Getting Started" and "Building the C++ Plugin" sections of the README to get your project set up and, in the particular case of your issue, the plugin built.
https://github.com/jacksondunstan/UnityNativeScripting#getting-started
