### ISSUE TITLE
WebGL support?

### ISSUE THREAD

**Issue by ZiadJ** [jacksondunstan/UnityNativeScripting#24]
Is there any plans for WebGL support in the future?

**Comment by jacksondunstan** [comment]
Hi @ZiadJ, I don't personally target WebGL so I probably won't dedicate the time to add support. That said, adding support should be rather easy. I think you'd just need to adjust the C++ plugin build by tweaking the [CMake file](https://github.com/jacksondunstan/UnityNativeScripting/blob/master/Unity/Assets/CppSource/CMakeLists.txt). If you do this, feel free to send me a pull request.
