### ISSUE TITLE
iOS build issue

### ISSUE THREAD

**Issue by HassanAliAnjum** [jacksondunstan/UnityNativeScripting#3]
I tried current code for iOS but it have some errors. So I tried using a single cpp file with one export method but the bundle created by make file gives linking error in iOS build created by Unity. can you please look into this or guide me.

**Comment by jacksondunstan** [comment]
Sorry to hear you're having trouble building for iOS, @HassanAliAnjum . I just tried and it's building fine for me. I didn't make any modifications to get it to build and you shouldn't have to either. Can you please provide your software versions (e.g. macOS, Xcode, iOS SDK) and the specific error you're getting?
