### ISSUE TITLE
A small idea to embed Python in C++

### ISSUE THREAD

**Issue by sekkit** [jacksondunstan/UnityNativeScripting#31]
Embedding Python by using Pythonnet(a .net cpython wrapper) is working with Unity.
But il2cpp compilation is very headache with that implementation. 
Will embed Python directly within UnityNativeScripting a solution?

**Comment by sekkit** [comment]
Explanation: why embed scripting languages, because of it's hot reload nature which is common practice in Commercial use.

**Comment by jacksondunstan** [comment]
Any C++ code you want to add to the native side should compile just fine. I don't know enough about embedding Python, but it seems like a possible use of this project.
