### ISSUE TITLE
Not working good in Windows

### ISSUE THREAD

**Issue by kitsek** [jacksondunstan/UnityNativeScripting#32]
The moving ball will become two static objects, not moving at all, and keeps flashing.
Unity2018.4.5

**Comment by jacksondunstan** [comment]
@zhangyl08, I haven't tried that exact Unity version, but it's working fine for me in Unity 2018.3.12f1 on Windows 10. Can you provide more information to help debug? Any logs, crash dumps, screenshots, software or hardware versions, or modifications you've made from a clean Git pull would be handy.

**Comment by sekkit** [comment]
hi, I did a test, the ball is not two static objects, but moving so fast, only from position a to b, no transitions.

**Comment by sekkit** [comment]
Also another problem I wanna address here:
The Standalone build has no material on that sphere. Red colored.

**Comment by jacksondunstan** [comment]
The purpose of the example scene is to provide something simple to show that the environment is correctly configured. It's not so much to provide smooth animations or pleasant graphics, so neither of these issues is much of a concern. It's expected that users will immediately delete the ball code and assets as soon as the "smoke test" passes and that's what I'd recommend here. That said, I'd happily accept if you'd like to submit a pull request to improve the animation or material.

**Comment by sekkit** [comment]
yup. im building a Unity framework based on UnityNativeScripting with python support.
When major problems solved I will create a new branch for that^^
