### ISSUE TITLE
How to debug in C++?

### ISSUE THREAD

**Issue by kitsek** [jacksondunstan/UnityNativeScripting#33]
newbie question.
get it running under macOS, wanna debug with Xcode.

**Comment by jacksondunstan** [comment]
Here are the steps:

1. Click the `Debug` menu (on the top bar)
2. Point at `Attach to Process`
3. Choose `Unity`
4. Set a breakpoint
5. Run in the editor to execute the breakpoint code
6. Debug in Xcode

Screenshot:
![Debugging_UnityNativeScripting](https://user-images.githubusercontent.com/192597/62403185-1f2a9500-b57b-11e9-990c-bc9302d55e49.png)
