### ISSUE TITLE
Hot reloading: Can't build over DLL in place.

### ISSUE THREAD

**Issue by daseyb** [jacksondunstan/UnityNativeScripting#4]
First of all, thanks for the great work! It helped me get started really quickly with hot reloading native plugins (even though I don't need any of the binding).

Windows locks DLL files that are currently in use, which means the linker can't write to it when you recompile.
This is fairly easily fixed by making a copy of the DLL and loading that instead. You still watch the original DLL for changes and delete the copy whenever you close the plugin.

**Comment by jacksondunstan** [comment]
Hi @daseyb, I'm glad this was helpful to you even if you're not using the bindings part of the project!

Thanks for reporting this issue with hot reloading on Windows and for providing a strategy to resolve the issue. Another approach that comes to mind is to unload the DLL before loading it again. I'll experiment with these ideas and hopefully one will solve the issue.

**Comment by daseyb** [comment]
The issue with that is that you need to have already overwritten the file
to detect that it changed in the auto reloader.
So you’d need to unload it in Unity just before the compiler tries to write
to it.

**Comment by jacksondunstan** [comment]
@daseyb I just pushed a commit to fix this issue using your approach. Please give it a try and let me know if you still have any trouble with hot reloading.
