### ISSUE TITLE
Define Arrays parameter caused an error

### ISSUE THREAD

**Issue by sekkit** [jacksondunstan/UnityNativeScripting#41]
```
                        "Name": "Game.Utils.Logger",
			"Methods": [
				{
					"Name": "info",
					"ParamTypes": [ 
						"System.Object[]" 
					] 
				},
                       ]

use of undefined type 'System::Array1<System::Object>'	NativeScript	C:\Projects\Research\unitycpp\Unity\Libs\CppSource\NativeScript\Bindings.cpp	5986	

```

**Comment by sekkit** [comment]
After reading issues and your blog, this problem is solved.
I strongly recommend simplify the type definition process... kinda complexity for newbies.

**Comment by jacksondunstan** [comment]
I'm glad to hear that you solved the problem. Please feel free to recommend any simplifications to the config file format.

**Comment by sekkit** [comment]
Yeah, I already modified the generatebinding a bit, but a editor/config tool is required in the future if use it in real project
