### ISSUE TITLE
Arrays: Generic is not a member of System::Collections

### ISSUE THREAD

**Issue by Jrius** [jacksondunstan/UnityNativeScripting#5]
Hello.
I've been running in an issue with arrays. As mentioned in your blog, I tried the following:
```
    "Arrays": [
        {
            "Type": "System.Single"
        }
    ]
```
However, once the bindings are generated, Visual Studio tells me that "Generic" does not exist in System::Collections, hence:
`template<> struct Array1<System::Single>`
cannot inherit from
`virtual System::Collections::Generic::IList<System::Single>`
I tried with other types, but the result is always the same. Out of curiosity, I also tried to add System.Collections.Generic.List to NativeScriptTypes.json, but GenerateBindings.cs fails to find that class.

Otherwise your library works great for pretty much everything else I've tried, and is simple enough to use. Your blogs also helps a lot understanding how to use it. This makes interfacing with other C++ libraries much easier. Great job !

**Comment by jacksondunstan** [comment]
Hi @Jrius ,

Sorry for the troubles! The code generator currently doesn't do any automatic discovery and generation of dependencies. So when you wanted to create a `float[]`, that meant that it needed to derive from `System.Collections.Generic.IList<float>` and, recursively, relied on several other types.

Currently, you'll have to manually add those dependencies to the JSON config to satisfy them. I started from the JSON config that's currently committed and got the same error as you. Then I kept on adding dependencies until the C++ compiler errors went away. Here's what I needed to add to get this array type working:

```javascript
{
	"Name": " System.IDisposable",
	"Methods": [
		{
			"Name": "Dispose",
			"ParamTypes": []
		}
	]
},
{
	"Name": "System.Collections.Generic.IEnumerator`1",
	"GenericParams": [
		{
			"Types": [
				"System.Single"
			]
		}
	],
	"Properties": [
		{
			"Name": "Current",
			"Get": {}
		}
	]
},
{
	"Name": "System.Collections.Generic.IEnumerable`1",
	"GenericParams": [
		{
			"Types": [
				"System.Single"
			]
		}
	],
	"Methods": [
		{
			"Name": "GetEnumerator",
			"ParamTypes": []
		}
	]
},
{
	"Name": "System.Collections.Generic.ICollection`1",
	"GenericParams": [
		{
			"Types": [
				"System.Single"
			]
		}
	]
},
{
	"Name": "System.Collections.Generic.IList`1",
	"GenericParams": [
		{
			"Types": [
				"System.Single"
			]
		}
	]
}
```

In a future version of the code generator, I hope to add in the ability to automatically discover dependencies so you don't have to add any of this to the JSON config and it "just works."

Sorry again for the troubles. I'm glad you're finding the project useful though! Please let me know if any other issues come up or if you have any suggestions for the project.

-Jackson

**Comment by Jrius** [comment]
Yup, that did it ! Finding Unity dependencies isn't a problem but those built-in types are a bit harder. Not a big issue though, and I'm impressed at how easy everything is with this library so far !
Thank you for your fast answer ! :)
