### ISSUE TITLE
Binding build error

### ISSUE THREAD

**Issue by lcals** [jacksondunstan/UnityNativeScripting#62]
cppSourceContents = InjectIntoString(
				cppSourceContents,
				"/*BEGIN FUNCTION POINTERS*/\n",
				"\n\t/*END FUNCTION POINTERS*/",
				builders.CppFunctionPointers.ToString());

	static string InjectIntoString(
			string contents,
			string beginMarker,
			string endMarker,
			string text)
		{
         int beginIndex = contents.IndexOf(beginMarker, startIndex);
				if (beginIndex < 0)
				{
					return contents;
				}
        }

error：
      Unable to split string correctly

WINDOWS  \r\n(0x0d, 0x0a)
MAC            \r(0x0d)
UNIX            \n(0x0a).

**Comment by jacksondunstan** [comment]
It's important to not change the line endings of the generated files for this reason. You can fix the issue by converting the line endings back.
