### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by hanbim520** [jacksondunstan/UnityNativeScripting#7]
<img width="858" alt="screen shot 2018-04-29 at 2 25 12 am" src="https://user-images.githubusercontent.com/7490792/39399676-b1ed3542-4b54-11e8-95df-a63c900f0dd6.png">
I build android only defined 
<img width="730" alt="screen shot 2018-04-29 at 2 26 38 am" src="https://user-images.githubusercontent.com/7490792/39399679-c406af56-4b54-11e8-815e-010c9a7ed2b1.png">

Another error,MacOS,auto build path is Plugins/NativeScript.bundle,but your project is need Editor folder

**Comment by jacksondunstan** [comment]
Hi @hanbim520, I just tried running CMake per the `README.md` instructions. Then I opened the project in Xcode and built it without errors. I also opened up the Unity project in 2017.3 and switched the Build Platform to Android, but didn't see any errors.

Could you please provide steps to reproduce the issue?

**Comment by hanbim520** [comment]
1.I create 3 platforms to compile instruction files
Mac OSX
zhanghaijunsMBP:build zhanghaijun$ cat makeMacosx.sh 
cmake .. -G "Xcode" -DEDITOR=TRUE ../CppSource/
iOS
zhanghaijunsMBP:buildIos zhanghaijun$ cat makeIos.sh 
cmake .. -G "Xcode" -DCMAKE_TOOLCHAIN_FILE=../CppSource/iOS.cmake ../CppSource 
Android
zhanghaijunsMBP:buildAndroid zhanghaijun$ cat makeAndroid.sh 
cmake -G Xcode -DANDROID_NDK=~/Downloads/android-ndk-r15c/ ../CppSource

Then All builded,as follows:
<img width="358" alt="screen shot 2018-05-01 at 3 06 37 pm" src="https://user-images.githubusercontent.com/7490792/39464639-4701186c-4d51-11e8-8e5c-97b0b8026c68.png">

Firstly,Build OSX binary error:
<img width="1423" alt="screen shot 2018-05-01 at 3 08 05 pm" src="https://user-images.githubusercontent.com/7490792/39464685-7c2ae4dc-4d51-11e8-8513-eb82c75869fd.png">

Secondly,iOS Xcode project error:
<img width="1440" alt="screen shot 2018-05-01 at 3 09 13 pm" src="https://user-images.githubusercontent.com/7490792/39464720-a05b1d04-4d51-11e8-8a6c-1958013160f4.png">

All look like the same error.

**Comment by hanbim520** [comment]
Unity Version
<img width="556" alt="screen shot 2018-05-01 at 3 30 51 pm" src="https://user-images.githubusercontent.com/7490792/39465212-af5eda90-4d54-11e8-86f3-87da46f35c67.png">

**Comment by jacksondunstan** [comment]
@hanbim520, thanks for providing these detailed instructions! I now realize that the problem wasn't in the Xcode build or the Unity Editor build, but a build for the target platform (e.g. to make an APK for Android). I was able to reproduce the issue and have pushed a commit with a fix for the issue:
97421db1ada4818fd8a496958125bbade14bc143
Please let me know if you run into any more issues.
